[package]
name = "websocket_red_or_black"
version = "0.1.0"
authors = ["mick"]

[dependencies]
ws = "0.7.8"
rand = "0.5.5"
serde_derive = "1.0.78"
serde_json = "1.0.27"
serde = "1.0.78"
env_logger = "0.5.13"
log = "0.4.5"
