[package]
name = "websocket_red_or_black"
version = "0.1.0"
authors = ["mick"]

[dependencies]
ws = "0.7.9"
rand = "0.6.5"
serde_derive = "1.0.87"
serde_json = "1.0.38"
serde = "1.0.87"
env_logger = "0.6.0"
log = "0.4.6"
